language: python
python: "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install libzbar-dev libopencv-dev libjpeg-dev python-dev doxygen swig
script:
  - .build/get-deps.sh 
  - python main.py