language: python
python: "2.7"
cache:
  directories:
    - /libwallaby # cache libwallaby
before_install:
  - chmod +x .build/get-deps.sh
  - .build/get-deps.sh
script:
  - rm wallaby.py # Remove our local copy of wallaby.py
  - python .build/add_path.py # Add wallaby.py (from libwallaby) to PATH
  - python main.py # Actually run the code!

after_failure:
  - cd ../../../../../../ # go to /
  - cd usr/lib
  - find wallaby.py

after_success:
  - echo About time!