language: python
python: "2.7"
cache:
  directories:
    - /libwallaby # cache libwallaby
before_install:
  - sudo apt-get update # update just in case
  - sudo apt-get install libzbar-dev libopencv-dev libjpeg-dev python-dev doxygen swig # get dependencies for libwallaby
  - git clone https://github.com/kipr/libwallaby.git
  - cd libwallaby && mkdir build && cd build
  - cmake .. && make
  - sudo make install

script:
  - cd 
  - cd build/ParksideRobotics/botball-2019 # return to home directory
  #- rm wallaby.py # Remove our local copy of wallaby.py
  - export PYTHONPATH="${PYTHONPATH}:home/travis/build/ParksideRobotics/botball-2019/libwallaby/lib/"
  - echo 'export PYTHONPATH="${PYTHONPATH}:home/travis/build/ParksideRobotics/botball-2019/libwallaby/lib/"' >> ~/.bashrc # Add wallaby.py (from libwallaby) to PATH
  - python main.py # Actually run the code!

after_failure:
  - python -c "import sys; print(':'.join(x for x in sys.path if x))"
  - cd /usr/lib
  - find wallaby.py

after_success:
  - echo About time!
